SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `#__redgit_callback` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `plugin` VARCHAR(255) NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `remote_ip` VARCHAR(255) NOT NULL,
  `data` TEXT NULL,
  `state` TINYINT(2) UNSIGNED NULL,
  `error_message` VARCHAR(255) NULL,
  `created_date` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '		',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET FOREIGN_KEY_CHECKS = 1;
